# Allow members of the nerc-ops group to list and view vaults.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    nerc.mghpcc.org/aggregate-to-nerc-ops: "true"
  name: vault.banzaicloud.com-view
rules:
  - apiGroups:
      - "vault.banzaicloud.com"
    resources:
      - vaults
    verbs:
      - list
      - get
      - watch
