apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  nerc.mghpcc.org/bundle: multicluster-engine-operator
resources:
- ../../base/core/namespaces/multicluster-engine-operator
- ../../base/operators.coreos.com/operatorgroups/multicluster-engine-operator
- ../../base/operators.coreos.com/subscriptions/multicluster-engine-operator
