apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/imageregistry.operator.openshift.io/configs/cluster
- ../../base/core/persistentvolumeclaims/image-registry-storage
