apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  nerc.mghpcc.org/kustomized: "true"

resources:
- ../common
- ../../base/core/namespaces/openshift-logging
- ../../bundles/acct-mgt
- ingresscontrollers/external-apps-ingress-controller.yaml
- externalsecrets
- apiserver/cluster.yaml
- secretstores

patches:
- path: ingresscontrollers/default_patch.yaml
