apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  nerc.mghpcc.org/kustomized: "true"

resources:
- ../common
- ../../bundles/acct-mgt
- ../../bundles/patch-operator
- ../../bundles/xdmod-reader
- feature/odf
- feature/custom-routes
- ../../base/core/namespaces/openshift-gitops
- externalsecrets
- apiserver/cluster.yaml
- secretstores
- issuers
- machineconfigs/configure-bond0
- nodenetworkconfigurationpolicies
- clusterversion.yaml
- certificates

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - config.yaml=configmaps/cluster-monitoring-config.yaml
  name: cluster-monitoring-config
  namespace: openshift-monitoring

patches:
- path: ingresscontrollers/default_patch.yaml
- path: oauths/cluster_patch.yaml
- path: patches/skipdryrunonmissingresource.yaml
  target:
    group: metallb.io
    name: .*
- path: patches/skipdryrunonmissingresource.yaml
  target:
    group: external-secrets.io
    name: .*
- path: patches/skipdryrunonmissingresource.yaml
  target:
    group: operator.external-secrets.io
    name: .*
- path: patches/skipdryrunonmissingresource.yaml
  target:
    group: nmstate.io
    name: .*
- path: patches/skipdryrunonmissingresource.yaml
  target:
    group: redhatcop.redhat.io
    name: .*
