apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: acct-mgt-secrets
spec:
  secretStoreRef:
    name: nerc-cluster-secrets
    kind: ClusterSecretStore
  refreshInterval: "1h"
  target:
    name: acct-mgt-secrets
    creationPolicy: 'Owner'
    deletionPolicy: "Retain"
    template:
      engineVersion: v2
  dataFrom:
    - extract:
        key: $ENV/$CLUSTER/acct-mgt/admin_password     # Patch $ENV/$CLUSTER in overlay
