apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nerc-allow-sys-admin
rules:
  - apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    resourceNames:
      - nerc-allow-sys-admin
    verbs:
      - use
