apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - externalsecrets
  - patches/logging-grafana-patch.yaml

patchesStrategicMerge:
  - grafanas/logging-grafana_patch.yaml
