apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    nerc.mghpcc.org/aggregate-to-nerc-ops: "true"
  name: nerc-ops-sudoer
rules:
  - apiGroups:
      - ""
      - user.openshift.io
    resourceNames:
      - system:admin
    resources:
      - systemusers
      - users
    verbs:
      - impersonate
  - apiGroups:
      - ""
      - user.openshift.io
    resourceNames:
      - system:masters
    resources:
      - groups
      - systemgroups
    verbs:
      - impersonate
