apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: curator-system
resources:
  - clusterroles
  - clusterrolebindings
  - deploymentconfigs
  - deployments
  - externalsecrets
  - rolebindings
  - roles
  - serviceaccounts
  - services
commonLabels:
  app.kubernetes.io/name: curator
