apiVersion: redhatcop.redhat.io/v1alpha1
kind: Patch
metadata:
  name: logging-grafana-patch
  namespace: grafana
spec:
  serviceAccountRef:
    name: patch-operator
  patches:
    logging-grafana-patch:
      targetObjectRef:
        apiVersion: integreatly.org/v1alpha1
        kind: Grafana
        name: logging-grafana
      patchTemplate: |
        spec:
          config:
            auth.generic_oauth:
              client_id: grafana
              client_secret: {{ (index . 1).data.GRAFANA_SECRET | b64dec }}
      patchType: application/merge-patch+json
      sourceObjectRefs:
      - apiVersion: v1
        kind: Secret
        name: oauth-client-secret
        namespace: grafana
