apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches:

- target:
    group: "redhatcop.redhat.io"
    name: ".*"
  patch: |
    - op: add
      path: /metadata/annotations/argocd.argoproj.io~1sync-options
      value: "SkipDryRunOnMissingResource=true"

- target:
    group: "metallb.io"
    name: ".*"
  patch: |
    - op: add
      path: /metadata/annotations/argocd.argoproj.io~1sync-options
      value: "SkipDryRunOnMissingResource=true"

- target:
    group: "external-secrets.io"
    name: ".*"
  patch: |
    - op: add
      path: /metadata/annotations/argocd.argoproj.io~1sync-options
      value: "SkipDryRunOnMissingResource=true"

- target:
    group: "operator.external-secrets.io"
    name: ".*"
  patch: |
    - op: add
      path: /metadata/annotations/argocd.argoproj.io~1sync-options
      value: "SkipDryRunOnMissingResource=true"

- target:
    group: "nmstate.io"
    name: ".*"
  patch: |
    - op: add
      path: /metadata/annotations/argocd.argoproj.io~1sync-options
      value: "SkipDryRunOnMissingResource=true"

- target:
    group: "redhatcop.redhat.io"
    name: ".*"
  patch: |
    - op: add
      path: /metadata/annotations/argocd.argoproj.io~1sync-options
      value: "SkipDryRunOnMissingResource=true"
