apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dex-config
spec:
  data:
  - remoteRef:
      key: nerc/nerc-ocp-infra/openshift-gitops/dex-config
      property: clientSecret
    secretKey: clientSecret
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: nerc-cluster-secrets
  target:
    name: dex-config
