apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  nerc.mghpcc.org/bundle: odf-external
resources:
- ../odf
- ../../base/odf.openshift.io/storagesystems/ocs-external-storagecluster-storagesystem
- ../../base/odf.openshift.io/storageclusters/ocs-external-storagecluster
- ../../base/storage.k8s.io/storageclasses/ocs-external-storagecluster-ceph-rbd
