apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-ocp-on-nerc
  namespace: group-sync-operator
spec:
  secretStoreRef:
    name: nerc-secret-store
    kind: SecretStore
  target:
    name: github-group-sync-token
  data:
  - secretKey: token
    remoteRef:
      key: nerc/nerc-ocp-prod/group-sync-operator/github-group-sync-token
      property: token
