apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-client-secret
  namespace: openshift-config
spec:
  secretStoreRef:
    name: nerc-secret-store
    kind: SecretStore
  target:
    name: github-client-secret
    template:
      metadata:
        labels: {}
  data:
  - secretKey: clientSecret
    remoteRef:
      key: nerc/nerc-ocp-prod/openshift-config/github-client-secret
      property: clientSecret
