apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: oauths-clientsecret-nerc
  namespace: openshift-config
spec:
  secretStoreRef:
    kind: SecretStore
    name: nerc-secret-store
  target:
    name: oauths-clientsecret-nerc
  data:
    - secretKey: clientSecret
      remoteRef:
        key: nerc/nerc-ocp-prod/openshift-config/oauths-clientsecret-nerc
        property: clientSecret
