apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-staging-dns01
spec:
  acme:
    email: help@nerc.mghpcc.org
    privateKeySecretRef:
      name: letsencrypt-production-key
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    solvers:
    - dns01:
        cnameStrategy: Follow
        route53:
          region: us-east-1
          accessKeyIDSecretRef:
            key: aws_access_key_id
            name: aws-route53-credentials
          secretAccessKeySecretRef:
            key: aws_secret_access_key
            name: aws-route53-credentials
      selector:
        dnsZones:
        - shift.nerc.mghpcc.org
