apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: xdmod-reader-permissions
subjects:
- kind: ServiceAccount
  name: xdmod-reader
  namespace: xdmod-reader
roleRef:
  kind: ClusterRole
  name: xdmod-permissions
  apiGroup: rbac.authorization.k8s.io
