apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-backup-s3-endpoint
spec:
  secretStoreRef:
    name: nerc-cluster-secrets
    kind: ClusterSecretStore
  refreshInterval: "1h"
  target:
    name: vault-backup-s3-endpoint
    creationPolicy: 'Owner'
    deletionPolicy: "Retain"
    template:
      engineVersion: v2
  data:
  - secretKey: ACCESS_KEY_ID
    remoteRef:
      key: nerc/nerc-ocp-infra/vault/backup/s3
      property: S3AccessKey
  - secretKey: SECRET_ACCESS_KEY
    remoteRef:
      key: nerc/nerc-ocp-infra/vault/backup/s3
      property: S3SecretKey
  - secretKey: ENDPOINT
    remoteRef:
      key: nerc/nerc-ocp-infra/vault/backup/s3
      property: S3EndPoint
  - secretKey: BUCKET
    remoteRef:
      key: nerc/nerc-ocp-infra/vault/backup/s3
      property: S3bucket
