apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vault

configMapGenerator:
  - name: vault-backup-config
    options:
      disableNameSuffixHash: true
    envs:
      - vault-backup-config.env

resources:
  - externalsecret.yaml
  - pvc.yaml
  - rolebinding.yaml
  - sa.yaml
  - task.yaml
  - trigger
