apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: external-apps
spec:
  # The "domain" setting does not automatically apply to routes as you might
  # expect; see https://github.com/OCP-on-NERC/operations/issues/41 for
  # details.
  domain: apps.shift.nerc.mghpcc.org
  defaultCertificate:
    name: external-apps-ingress-certificate
  endpointPublishingStrategy:
    type: LoadBalancerService
    loadBalancer:
      scope: External
  nodePlacement:
    nodeSelector:
      matchLabels:
        nerc.mghpcc.org/external-ingress: 'true'
  routeSelector:
    matchLabels:
      nerc.mghpcc.org/external-ingress: 'true'
