apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
- path: patches/skipdryrunonmissingresource.yaml
  target:
    group: metallb.io
    name: .*
- path: patches/skipdryrunonmissingresource.yaml
  target:
    group: external-secrets.io
    name: .*
- path: patches/skipdryrunonmissingresource.yaml
  target:
    group: operator.external-secrets.io
    name: .*
- path: patches/skipdryrunonmissingresource.yaml
  target:
    group: nmstate.io
    name: .*
- path: patches/skipdryrunonmissingresource.yaml
  target:
    group: redhatcop.redhat.io
    name: .*
