apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  name: nerc-ocp-prod
  labels:
    name: nerc-ocp-prod
    cloud: auto-detect
    vendor: auto-detect
    cluster.open-cluster-management.io/clusterset: default
  annotations: {}
spec:
  hubAcceptsClient: true
