kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: db-noobaa-db-pg-0
  namespace: openshift-storage
  labels:
    app: noobaa
    noobaa-db: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  storageClassName: ocs-external-storagecluster-ceph-rbd
  volumeMode: Filesystem
