apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  nerc.mghpcc.org/bundle: cluster-admin-rbac
resources:
- ../../base/rbac.authorization.k8s.io/clusterrolebindings/cluster-admins-nerc-sudoer
- ../../base/rbac.authorization.k8s.io/clusterrolebindings/cluster-admins-nerc-reader
- ../../base/user.openshift.io/groups/cluster-admins
- ../../base/rbac.authorization.k8s.io/clusterroles/allow-portforward-all
- ../../base/rbac.authorization.k8s.io/clusterrolebindings/cluster-admins-nerc-portforward
