apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - operatorgroups
  - subscriptions
  - grafanas
  - grafanadatasources
  - routes
  - serviceaccounts
commonLabels:
  app.kubernetes.io/name: grafana
  app.kubernetes.io/component: grafana
  app.kubernetes.io/part-of: cluster-logging
