apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: loki-thanos-object-storage
  namespace: openshift-logging
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: nerc-cluster-secrets
    kind: ClusterSecretStore
  target:
    name: thanos-object-storage
  dataFrom:
    - extract:
        key: $ENV/$CLUSTER/loki-thanos-object-storage
