apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  nerc.mghpcc.org/bundle: console
resources:
- ../../base/operator.openshift.io/consoles/cluster
- ../../base/core/configmaps/nerc-logo
