apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-admins-nerc-portforward
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: allow-portforward-all
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: cluster-admins
