apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  nerc.mghpcc.org/bundle: openshift-operators-redhat
resources:
- ../../base/core/namespaces/openshift-operators-redhat/
- ../../base/operators.coreos.com/operatorgroups/openshift-operators-redhat
