apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  nerc.mghpcc.org/bundle: openshift-gitops
resources:
- ../../base/operators.coreos.com/subscriptions/openshift-gitops-operator
- ../../base/rbac.authorization.k8s.io/clusterroles/argocd-allow-all/
- ../../base/rbac.authorization.k8s.io/clusterrolebindings/argocd-allow-all/
