apiVersion: redhatcop.redhat.io/v1alpha1
kind: GroupSync
metadata:
  name: github-ocp-on-nerc
  namespace: group-sync-operator
spec:
  # synchronize every 4 hours
  schedule: "0 */4 * * *"
  providers:
    - name: github
      github:
        organization: ocp-on-nerc
        prune: true
        credentialsSecret:
          name: github-group-sync
          namespace: group-sync-operator
