apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/operators.coreos.com/subscriptions/acm
- ../../base/core/namespaces/open-cluster-management
- ../../base/operators.coreos.com/operatorgroups/open-cluster-management
