apiVersion: logging.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: instance
  namespace: openshift-logging
spec:
  outputs:
    - name: loki-app
      type: loki
      url: https://lokistack-openshift-operators-redhat.apps.nerc-ocp-infra.rc.fas.harvard.edu/api/logs/v1/application
      secret:
        name: lokistack-gateway-bearer-token
      loki:
        labelKeys:
          - log_type
          - level
          - service
          - kubernetes.namespace_name
          - kubernetes.pod_name
          - kubernetes.host
          - kubernetes.labels
    - name: loki-infra
      type: loki
      url: https://lokistack-openshift-operators-redhat.apps.nerc-ocp-infra.rc.fas.harvard.edu/api/logs/v1/infrastructure
      secret:
        name: lokistack-gateway-bearer-token
      loki:
        labelKeys:
          - log_type
          - level
          - service
          - kubernetes.namespace_name
          - kubernetes.pod_name
          - kubernetes.host
          - kubernetes.labels
    - name: loki-audit
      type: loki
      url: https://lokistack-openshift-operators-redhat.apps.nerc-ocp-infra.rc.fas.harvard.edu/api/logs/v1/audit
      secret:
        name: lokistack-gateway-bearer-token
      loki:
        labelKeys:
          - log_type
          - level
          - service
          - kubernetes.namespace_name
          - kubernetes.pod_name
          - kubernetes.host
          - kubernetes.labels
  pipelines:
    - name: send-app-logs
      inputRefs:
      - application
      outputRefs:
      - loki-app
    - name: send-infra-logs
      inputRefs:
      - infrastructure
      outputRefs:
      - loki-infra
    - name: send-audit-logs
      inputRefs:
      - audit
      outputRefs:
      - loki-audit
