apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    nerc.mghpcc.org/aggregate-to-nerc-ops: "true"
  name: nerc-ops-portforward
rules:
  - apiGroups:
      - ""
    resources:
      - pods/portforward
    verbs:
      - '*'
