apiVersion: metallb.io/v1beta1
kind: AddressPool
metadata:
  name: public
  namespace: metallb-system
spec:
  protocol: layer2
  autoAssign: false
  addresses:
    - 199.94.61.6/32
    - 199.94.61.240/28
