kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: vault-ui
  namespace: vault
spec:
  to:
    kind: Service
    name: nerc-vault
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  port:
    targetPort: http
