apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: default
  namespace: openshift-ingress-operator
spec:
  defaultCertificate:
    name: default-ingress-certificate
  routeSelector:
    matchExpressions:
      - key: nerc.mghpcc.org/external-ingress
        operator: NotIn
        values:
          - "true"
