apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: apiserver-secret-store
  namespace: openshift-config
spec:
  provider:
    vault:
      server: "http://nerc-vault.vault.svc:8200"
      path: "nerc"
      version: "v2"
      auth:
        kubernetes:
          mountPath: kubernetes/nerc-ocp-prod/openshift-api
          role: secret-reader
          serviceAccountRef:
            name: "vault-secret-reader"
            namespace: "external-secrets-operator"
