apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patchesStrategicMerge:
  - externalsecrets/loki-thanos-object-storage_patch.yaml
  - externalsecrets/openshift-logging-lokistack-gateway-bearer-token_patch.yaml
