apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: vlan-211
spec:
  nodeSelector:
    kubernetes.io/hostname: "wrk-5"
  desiredState:
    interfaces:
    - name: eno1np0.211
      type: vlan
      state: up
      ipv4:
        # DHCP for this network is currently managed by Neutron, and Neutron is
        # unable to provide DHCP service to trunked interfaces. We need to manually
        # manage address assignment here until we move DHCP away from Neutron.
        enabled: true
        dhcp: false
        auto-routes: false
        address:
        - ip: 10.0.120.39
          prefix-length: 22
      vlan:
        base-iface: eno1np0
        id: 211
      mtu: 9000
    routes:
      config:
      - destination: 10.255.116.0/23
        next-hop-address: 10.0.120.1
        next-hop-interface: vlan-211
      - destination: 10.247.236.0/25
        next-hop-address: 10.0.120.1
        next-hop-interface: vlan-211
      - destination: 140.247.236.0/25
        next-hop-address: 10.0.120.1
        next-hop-interface: vlan-211
