apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: acct-mgt-secrets
spec:
  target:
    name: acct-mgt-secrets
  secretStoreRef:
    name: nerc-secret-store
    kind: SecretStore
  dataFrom:
    - extract:
        key: nerc/nerc-ocp-prod/acct-mgt/admin_password
