apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: acct-mgt
resources:
  - ../../base
patchesStrategicMerge:
  - patches/configmap_patch.yaml
  - patches/deployment_patch.yaml
  - patches/externalsecret_patch.yaml
