apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../common
- ../../base/operators.coreos.com/subscriptions/openshift-gitops-operator
- ../../base/rbac.authorization.k8s.io/clusterroles/openshift-gitops-openshift-gitops-argocd-application-controller
- clusterversion.yaml
