apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  nerc.mghpcc.org/kustomized: "true"
resources:
- ../common
- ../../bundles/openshift-gitops
- ../../bundles/acm
- ../../bundles/odf
- ../../base/operator.openshift.io/networks/cluster
- clusterversion.yaml
- machineconfigs/disable-net-ifnames.yaml
- machineconfigs/mellanox-udev-rules
- machineconfigs/configure-bond0
- nodenetworkconfigurationpolicies/vlan-2177-nese.yaml

patches:
  - path: oauths/cluster_patch.yaml
  - path: groups/cluster-admins_patch.yaml
