apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../common
- ../../bundles/openshift-gitops
- ../../bundles/acm
- ../../base/operators.coreos.com/subscriptions/cert-manager
- clusterversion.yaml
